### ISSUE TITLE
What about ruby less than 2 

### ISSUE THREAD

**Issue by penfold45** [mime-types/mime-types-data#1]
Hi

You appear to have no branches and from what I can tell from your recent commits this gem now requires ruby 2.

I use an old version of the fog gem via an elastic search chef cookbook which eventually depends on this gem but I am also running on an old version of chef which uses Ruby 1.9.

Now I cannot boot new elastic search servers because I do not have ruby 2. Any chance of a tag from before you required Ruby 2?

**Comment by halostatue** [comment]
So, you’re looking at the wrong repo. What you’re looking for is the [`mime-types` gem](https://github.com/mime-types/ruby-mime-types), not the `mime-types-data` gem. This gem is used by mime-types 3 or later, which requires Ruby 2.0 or later.

When I released mime-types 3 yesterday (requires Ruby 2.0 or later), I also released mime-types 2.99 (requires Ruby 1.9.2 or later). If there is a Gemfile in what you’re running, add: `gem 'mime-types', [ '>= 2.6.2', '< 3' ]` to it and you should be OK.
