### ISSUE TITLE
Adobe Illustrator files should use application/pdf

### ISSUE THREAD

**Issue by Alhadis** [mime-types/mime-types-data#22]
This gem lists `.ai` files as `application/postscript`, but Adobe Illustrator hasn't used EPS as its native format since 2000 or so. Version 9 and onwards save artwork as ordinary PDFs with editor-specific metadata included.

See github/linguist#4572 for a related discussion.

/cc @lildude

**Comment by halostatue** [comment]
I have not problem with this change, but I do not see having the time to make the change for a few weeks (even though it’s small). I can probably get a PR merged and released by next weekend if you submit a PR for the change (all you need to change are the `.yml` files; the tooling takes care of the rest).

**Comment by Alhadis** [comment]
Alright, done. Please let me know if there's anything I've missed. 👍
