### ISSUE TITLE
use image/bmp

### ISSUE THREAD

**Issue by wtn** [mime-types/mime-types-data#48]
This gem prefers `image/x-bmp` ([reference](https://github.com/mime-types/mime-types-data/blob/219ebc3045839daafab93227c69c14bb5afd7be1/data/content_type_mime.db#L734)) but `image/bmp` should be used instead.

`image/bmp` is documented here: https://www.iana.org/assignments/media-types/image/bmp

**Comment by wtn** [comment]
Closing at the issue appears to be in Rails, not this gem.

**Comment by halostatue** [comment]
I believe that this is a correct change. It appears that at one point `image/bmp` was _not_ registered and we never updated it when it did become registered.

**Comment by halostatue** [comment]
I have released 3.2022.0105 with this fix.
