### ISSUE TITLE
YAML data

### ISSUE THREAD

**Issue by voxik** [mime-types/mime-types-data#5]
Your readme claims the following:

> This registry contains the MIME media types in three formats:
> 
>    A YAML format matching the Ruby mime-types library objects (MIME::Type). This is the primary user-editable format.

So I'd expect that the gem ships the YAML data as well, but that is not true. Could you please clarify the readme a bit? Or the gem of course ...

Thank you.

**Comment by halostatue** [comment]
Updated with the 2018-08-12 release to clarify that the YAML files are not and will not be shipped with the gem due to size considerations.
