### ISSUE TITLE
MIME::Types.type_for Does not Support JFIF Extension

### ISSUE THREAD

**Issue by mohammedgad** [mime-types/mime-types-data#51]
Hi!
Recently I wanted to use `MIME::Types.type_for` to detect a file content type, but I receive nothing when I try to detect the content type of a JFIF file.

```ruby
MIME::Types.type_for("something.jpeg")
=> [#<MIME::Type: image/jpeg>]
MIME::Types.type_for("something.jfif")
=> []
```

Expected result:
This should return `[#<MIME::Type: image/jpeg>]`

Actual result: 
it returns an empty array

**Comment by halostatue** [comment]
MIME::Types returns data provided by `mime-types-data`. A pull request here to add `jfif` to `image/jpeg` (*only* in the `images` YAML file) would be accepted.

**Comment by mohammedgad** [comment]
Thank you @halostatue for your response! May I open a PR to add it?
