### ISSUE TITLE
All `js` mime types marked as obsolete?

### ISSUE THREAD

**Issue by ioquatix** [mime-types/mime-types-data#55]
```
> MIME::Types.of("js").map(&:obsolete?)
=> [true, true, true]
```

Was this the case before? I don't think so?

**Comment by halostatue** [comment]
Good catch. Digging through https://www.iana.org/assignments/media-types/media-types.xml, it appears that `application/javascript` has been deprecated in favour of `text/javascript`, but that appears to be a reversal from decisions made in 2015.

I have just released 3.2023.0218.1 to fix this.

**Comment by ioquatix** [comment]
Thanks for turning this around quickly, FYI it was breaking things on my end lol.

**Comment by ioquatix** [comment]
Kind of curious if you know why, what's the rational between `application/whatever` and `text/whatever`? Like, are they planning to use `text/json` too?

**Comment by halostatue** [comment]
Your request had me dig a bit deeper. RFC4329 (April 2006) originally deprecated `text/javascript` in favour of `application/javascript` and `text/ecmascript` in favour of `application/ecmascript`. So my decision wasn’t arbitrary.

RFC9239 (May 2022) reverses this because history, common usage, and WHATWG HTML5 disagreed:

> ## [6. ](https://www.rfc-editor.org/rfc/rfc9239.html#section-6)[IANA Considerations](https://www.rfc-editor.org/rfc/rfc9239.html#name-iana-considerations)
>
> The media type registrations herein are divided into two major categories: (1) the sole media type "text/javascript", which is now in common usage and (2) all of the media types that are obsolete (i.e., "application/ecmascript", "application/javascript", "application/x-ecmascript", "application/x-javascript", "text/ecmascript", "text/javascript1.0", "text/javascript1.1", "text/javascript1.2", "text/javascript1.3", "text/javascript1.4", "text/javascript1.5", "text/jscript", "text/livescript", and "text/x-ecmascript").
>
> For both categories, the "Published specification" entry for the media types is updated to reference [[ECMA-262](https://www.rfc-editor.org/rfc/rfc9239.html#ECMA-262)]. In addition, a new file extension of .mjs has been added to the list of file extensions with the restriction that contents should be parsed using the Module goal. Finally, the [[HTML](https://www.rfc-editor.org/rfc/rfc9239.html#HTML)] specification uses "text/javascript" as the default media type of ECMAScript when preparing script tags; therefore, "text/javascript" intended usage has been moved from OBSOLETE to COMMON.
>
> These changes have been reflected in the IANA "Media Types" registry in accordance with [[RFC6838](https://www.rfc-editor.org/rfc/rfc9239.html#RFC6838)]. All registrations will point to this document as the reference. The outdated note stating that the "text/javascript" media type has been "OBSOLETED in favor of application/javascript" has been removed. The outdated note stating that the "text/ecmascript" media type has been "OBSOLETED in favor of application/ecmascript" has been removed. IANA has added the note "OBSOLETED in favor of text/javascript" to all registrations except "text/javascript"; that is, this note has been added to the "text/ecmascript", "application/javascript", and "application/ecmascript" registrations.
>
> Four of the legacy media types in this document have a subtype starting with the "x-" prefix:
>
> - application/x-ecmascript
> - application/x-javascript
> - text/x-ecmascript
> - text/x-javascript
>
> Note that these are grandfathered media types registered as per [Appendix A](https://www.rfc-editor.org/rfc/rfc6838#appendix-A) of [[RFC6838](https://www.rfc-editor.org/rfc/rfc9239.html#RFC6838)]. These registrations predate [BCP 178](https://www.rfc-editor.org/rfc/rfc9239.html#RFC6648) [[RFC6648](https://www.rfc-editor.org/rfc/rfc9239.html#RFC6648)], which they violate, and are only included in this document for backward compatibility.

I’ve opened #56 to cover the documented types and deprecations further.
