### ISSUE TITLE
audio/wav not recognized

### ISSUE THREAD

**Issue by kevingriffin** [mime-types/mime-types-data#9]
`audio/x-wav` exists, but `audio/wav` is missing. WAV has been standardized for a long time—can we add it?

**Comment by halostatue** [comment]
`audio/wav` is not in the IANA MIME type registry for [`audio/`](https://www.iana.org/assignments/media-types/media-types.xhtml#audio). When it is added, a regular data update will pick it up. Until then, `audio/wav` is not the MIME type for [WAV](https://en.wikipedia.org/wiki/WAV).
